on:
  workflow_dispatch:
  push:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v2
      - name: 🔎 Check_IP
        id: ip
        run: curl https://api.ipify.org
          echo ${{steps.id.ip}}
