on:
  workflow_dispatch:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v2
      - name: 🔎 Check_IP
        id: ip
        run: curl https://api.ipify.org
      -  name: Print Public IP
         run: |
          echo ${{env.Check_IP}}
